# Import the Library

In [1]:
import pandas as pd
import numpy as np

# Read The Excel File

In [2]:
beauty = pd.read_excel(
    r"C:\Users\SHUSHREE SWAIN\OneDrive\Desktop\Beauty_sales original\Data(Raw & Cleaned)\GlowCart_Beauty.xlsx")

In [3]:
beauty

,Order_ID,Order_Date,Region,Sales_Channel,Product_Name,Qty_Sold,Unit_Price_(₹),Discount_%,COGS_Per_Unit_(₹),Sales_Rep
0,BT-00092,2023-01-01,West,Online,Matte Lipstick,52,310.000,34.20000,94.18,Nidhi C
1,BT-00531,2023-01-01,North,Modern Trade,BB Cream 30ml,4,560.000,8.60000,231.90,Anjali M
2,BT-00761,2023-01-01,Central,Salon Wholesale,Nail Polish Set (12pc),57,620.000,6.00000,287.12,Sunita P
3,BT-00770,2023-01-01,East,General Trade,Mascara,21,560.000,7.50000,209.61,Sneha B
4,BT-00806,2023-01-01,West,Salon Wholesale,Vitamin C Face Serum 30ml,8,770.000,26.10000,231.15,Rahul D
...,...,...,...,...,...,...,...,...,...,...
4996,BT-03853,2023-12-31,West,General Trade,Night Repair Cream 50ml,8,910.000,38.30000,351.08,Priya S
4997,BT-04158,2023-12-31,East,Online,Hair Oil 200ml,9,310.000,12.90000,118.02,Meena G
4998,BT-04303,2023-12-31,Central,Salon Wholesale,Mascara,10,380.000,6.50000,160.02,Vikram N
4999,BT-04703,2023-12-31,Central,Salon Wholesale,Hair Oil 200ml,34,390.000,12.30000,149.45,Suresh K
5000,TOTALS,NaN,NaN,NaN,NaN,154145,557.204,16.53242,NaN,NaN

# Check data

In [4]:
beauty.shape

(5001, 10)

In [5]:
beauty.columns

Index(['Order_ID', 'Order_Date', 'Region', 'Sales_Channel', 'Product_Name',
       'Qty_Sold', 'Unit_Price_(₹)', 'Discount_%', 'COGS_Per_Unit_(₹)',
       'Sales_Rep'],
      dtype='object')

In [6]:
beauty.columns = ['Order_ID', 'Order_Date', 'Region', 'Sales_Channel', 'Product_Name',
    'Qty_Sold', 'Unit_Price', 'Discount_Percent', 'COGS_Per_Unit', 'Sales_Rep']

In [7]:
beauty.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5001 entries, 0 to 5000
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          5001 non-null   object
 1   Order_Date        5000 non-null   object
 2   Region            5000 non-null   object
 3   Sales_Channel     5000 non-null   object
 4   Product_Name      5000 non-null   object
 5   Qty_Sold          5001 non-null   int64
 6   Unit_Price        5001 non-null   float64
 7   Discount_Percent  5001 non-null   float64
 8   COGS_Per_Unit     5000 non-null   float64
 9   Sales_Rep         5000 non-null   object
dtypes: float64(3), int64(1), object(6)
memory usage: 390.8+ KB

In [8]:
beauty.describe()

            Qty_Sold   Unit_Price  Discount_Percent  COGS_Per_Unit
count    5001.000000  5001.000000       5001.000000    5000.000000
mean       61.645671   557.204000         16.532420     213.602594
std      2179.352180   394.033022         10.047415     186.470073
min         2.000000   120.000000          4.000000      32.560000
25%        16.000000   330.000000          8.600000     107.427500
50%        31.000000   470.000000         12.600000     175.175000
75%        46.000000   650.000000         24.000000     248.185000
max    154145.000000  2800.000000         44.000000    1436.570000

# Missing values

In [9]:
beauty.isnull().sum()

Order_ID            0
Order_Date          1
Region              1
Sales_Channel       1
Product_Name        1
Qty_Sold            0
Unit_Price          0
Discount_Percent    0
COGS_Per_Unit       1
Sales_Rep           1
dtype: int64

# Remove null value

In [10]:
beauty.dropna(inplace=True)

In [11]:
beauty.isnull().sum()

Order_ID            0
Order_Date          0
Region              0
Sales_Channel       0
Product_Name        0
Qty_Sold            0
Unit_Price          0
Discount_Percent    0
COGS_Per_Unit       0
Sales_Rep           0
dtype: int64

# Check Duplicate

In [12]:
beauty.duplicated().sum()

0

In [13]:
beauty.dtypes

Order_ID             object
Order_Date           object
Region               object
Sales_Channel        object
Product_Name         object
Qty_Sold              int64
Unit_Price          float64
Discount_Percent    float64
COGS_Per_Unit       float64
Sales_Rep            object
dtype: object

# Convert date

In [14]:
beauty['Order_Date'] = pd.to_datetime(beauty['Order_Date'])

In [15]:
beauty

,Order_ID,Order_Date,Region,Sales_Channel,Product_Name,Qty_Sold,Unit_Price,Discount_Percent,COGS_Per_Unit,Sales_Rep
0,BT-00092,2023-01-01,West,Online,Matte Lipstick,52,310.0,34.2,94.18,Nidhi C
1,BT-00531,2023-01-01,North,Modern Trade,BB Cream 30ml,4,560.0,8.6,231.90,Anjali M
2,BT-00761,2023-01-01,Central,Salon Wholesale,Nail Polish Set (12pc),57,620.0,6.0,287.12,Sunita P
3,BT-00770,2023-01-01,East,General Trade,Mascara,21,560.0,7.5,209.61,Sneha B
4,BT-00806,2023-01-01,West,Salon Wholesale,Vitamin C Face Serum 30ml,8,770.0,26.1,231.15,Rahul D
...,...,...,...,...,...,...,...,...,...,...
4995,BT-02595,2023-12-31,North,Pharmacy,BB Cream 30ml,30,630.0,9.2,239.27,Anjali M
4996,BT-03853,2023-12-31,West,General Trade,Night Repair Cream 50ml,8,910.0,38.3,351.08,Priya S
4997,BT-04158,2023-12-31,East,Online,Hair Oil 200ml,9,310.0,12.9,118.02,Meena G
4998,BT-04303,2023-12-31,Central,Salon Wholesale,Mascara,10,380.0,6.5,160.02,Vikram N
4999,BT-04703,2023-12-31,Central,Salon Wholesale,Hair Oil 200ml,34,390.0,12.3,149.45,Suresh K

In [16]:
for i in beauty.columns:
    print(f"{i}: \n {beauty[i].unique()}\n")

Order_ID:
 ['BT-00092' 'BT-00531' 'BT-00761' ... 'BT-04158' 'BT-04303' 'BT-04703']

Order_Date:
 <DatetimeArray>
['2023-01-01 00:00:00', '2023-01-02 00:00:00', '2023-01-03 00:00:00',
 '2023-01-04 00:00:00', '2023-01-05 00:00:00', '2023-01-06 00:00:00',
 '2023-01-07 00:00:00', '2023-01-08 00:00:00', '2023-01-09 00:00:00',
 '2023-01-10 00:00:00',
 ...
 '2023-12-22 00:00:00', '2023-12-23 00:00:00', '2023-12-24 00:00:00',
 '2023-12-25 00:00:00', '2023-12-26 00:00:00', '2023-12-27 00:00:00',
 '2023-12-28 00:00:00', '2023-12-29 00:00:00', '2023-12-30 00:00:00',
 '2023-12-31 00:00:00']
Length: 365, dtype: datetime64[ns]

Region:
 ['West' 'North' 'Central' 'East' 'South']

Sales_Channel:
 ['Online' 'Modern Trade' 'Salon Wholesale' 'General Trade' 'Pharmacy']

Product_Name:
 ['Matte Lipstick' 'BB Cream 30ml' 'Nail Polish Set (12pc)' 'Mascara'
 'Vitamin C Face Serum 30ml' 'Lip Gloss' 'Blush Palette' 'Face Wash 100ml'
 'Under Eye Cream 15ml' 'Hydrating Moisturiser 50ml'
 'Micellar Cleansing Water' 'Kajal Eye Pencil' 'SPF 50 Sunscreen 100g'
 'Compact Powder' 'Rose Water Toner 200ml' 'Night Repair Cream 50ml'
 'Eyeshadow Palette 9-shade' 'Hair Oil 200ml' 'Hair Serum 100ml'
 'Perfume 100ml EDP']

Qty_Sold:
 [52  4 57 21  8  5 42 23 26 37 48 53  6 43 33 56 19 18 35 59 30 54 60 25
 14 13 11 29 24 34 45 17 36 51 44 47 58  2 22 31  3 20 15 12 50 16 10 32
 55  9 40 27 41 28 49 38 39  7 46]

Unit_Price:
 [ 310.  560.  620.  770.  270.  800.  240.  810.  390.  450.  500.  650.
  290.  870.  260.  840.  480.  380.  180.  340.  220.  350.  320.  640.
  590.  250.  570.  790.  460.  430.  820.  440.  740.  530.  510.  610.
  550.  360.  490.  190.  420.  760.  900.  170.  860. 2580.  540.  330.
  410.  630.  700.  230.  660.  830.  580.  470. 2020.  710.  400. 2710.
 1500.  720.  600.  300.  200.  130.  750.  730.  280. 2550.  210.  780.
  370. 1110.  880.  970.  690. 1170.  850.  520.  140. 2730. 1160.  150.
 1560. 1760. 2330.  960. 2450.  930.  950.  160.  890. 1520. 1910.  670.
 2030. 2270. 2390. 1430.  990. 1630.  680. 2150. 1180. 1130. 2560. 1640.
 1780.  910.  920. 1060. 2610. 2770. 2480. 1750.  120. 1980. 2200. 1800.
 1690. 1920. 1220. 1410. 1010.  940. 2250. 2380. 2400. 1140. 1270. 2460.
 1850. 2790. 1480. 2340. 1050. 2220. 1210. 1030. 2700. 2410. 2140. 1080.
 2000. 2760. 1830. 1150. 1070. 2740. 2010. 1890. 1100. 1950. 2280. 1710.
 1940. 2210. 2520. 1870. 2130. 2600. 2470. 2190. 1350. 2670. 1930. 1440.
 1190. 2240. 1250. 1090. 2440. 2170. 1120. 2510. 1880. 1620. 1230. 1300.
 1570. 1340. 2160. 1330. 2780. 1020. 1400. 1990. 1000. 1290. 2500. 1970.
 2720. 1040. 1390.  980. 2120. 1730. 1360. 2750. 2530. 2110. 2420. 1960.
 2260. 2620. 1680. 1320. 1540. 2650. 1700. 1510. 1770. 2360. 1600. 1900.
 1740. 2490. 2630. 1280. 1590. 2310. 2660. 1860. 2230. 2050. 2800. 1450.
 1820.]

Discount_Percent:
 [34.2  8.6  6.   7.5 26.1  9.3 25.8  8.4 12.2 19.2 20.2 12.4 34.8 33.1
 34.5 12.5  7.1  7.  35.4 42.4 10.4  4.2  6.4 12.1  5.4 20.9  7.2 10.3
 11.1 15.4 10.  15.5 10.6  8.   4.3 14.5 30.1 28.  32.8  6.8 12.6 12.
 11.2  8.5 36.7  8.1 38.9 11.  27.7  6.3 37.6 29.3  7.4 21.  14.2 10.5
 19.9 24.4 13.   9.6 12.7 24.7  9.5 11.5  6.2 20.6 11.4 28.9 19.6  5.2
 18.6  9.4 14.8 12.9  6.5  7.6 15.   4.1 27.4  8.9  6.7  9.   5.7 22.3
 15.9 11.9 14.  11.6  6.1 22.4 19.8 24.6 11.3 15.3 38.6  5.1 38.7 38.1
 35.8 17.1 42.8 23.1  6.9 29.9 31.6 10.1 13.1 29.8 13.3  9.9 22.  17.4
 28.7 12.3 18.7 13.7 16.6  8.2 29.4 21.1 21.6 27.2  9.2  4.8 26.9 31.
 27.1 29.   5.8 32.5  6.6 24.1  7.9 26.  11.7 24.3 13.9 14.3  5.5 30.2
 36.6 31.2 28.6  7.3 30.7 13.5 42.3 18.9 29.7 33.9 22.2  5.6 27.3 29.2
 38.8 20.4 15.1 23.9  8.7  8.8 15.2 11.8  7.8 23.5 10.2 21.9 36.4 40.6
 33.4 28.2 43.3 32.7  9.8 18.2 41.2 37.4 23.6 36.9  9.7 23.7 35.  40.
  4.4 35.6  7.7 36.5 16.5 39.2  9.1  4.9 13.4 32.1 13.2 19.7 26.5 16.3
 16.2 25.9 14.6 12.8 22.1 16.  18.  30.8 24.8 22.7  5.9 17.   5.3 39.
 10.8 15.6 37.8 21.4 20.5 42.7 18.4 31.8 39.9 31.9  8.3 21.2 27.8 35.2
 39.7 23.2 36.2 30.3 41.1 28.1 19.5 10.7 43.8 13.8  4.7 22.6 41.3 23.3
 26.2 10.9 30.4 13.6 37.2 28.3 33.2 26.6 15.7 31.5 20.1 35.5 37.7 24.5
 14.4 30.  36.1 41.4 28.5 27.5 23.4 23.8 32.2 41.7 25.  26.4 14.1 27.6
 35.7 16.8 22.8 41.  17.3 39.8 40.2 21.5 34.1 25.3 17.9 17.8 26.8 32.
 30.9 25.7 18.5 25.4 25.6 31.3 34.6 39.4 29.1 26.3  4.6 18.3 19.4 20.
 21.3 17.6 28.4 19.  27.  17.5 24.9 16.4 41.9 38.2 40.3 30.6 23.  22.5
 39.1 38.  32.3 33.6 18.8 19.3  5.  21.8 20.8 14.9 38.5 27.9 42.  25.2
 19.1 36.8 34.4 33.3 36.  22.9 16.9  4.  37.  15.8 34.3 40.9 18.1 38.4
 20.7 33.5 24.2 39.5 14.7 35.9 41.8 31.7 17.2 31.1 43.6 33.  37.3 38.3
 34.  24.  32.4 21.7 20.3 34.9 42.5 35.3 31.4 17.7 34.7 28.8 26.7 37.5
 33.8 37.1 25.5 29.5 32.6 42.6 43.4  4.5 25.1 40.1 42.1 16.7 40.7 43.
 43.7 35.1 16.1 40.4 33.7 37.9 32.9 39.3 39.6 30.5 29.6 36.3 44.  40.5
 42.9 43.9 41.5 40.8]

COGS_Per_Unit:
 [ 94.18 231.9  287.12 ... 239.27 351.08 118.02]

Sales_Rep:
 ['Nidhi C' 'Anjali M' 'Sunita P' 'Sneha B' 'Rahul D' 'Deepa S' 'Meena G'
 'Rohit K' 'Suresh K' 'Anand V' 'Priya S' 'Priya R' 'Vikram N' 'Pooja N'
 'Kiran T']

# Year

In [17]:
beauty['Year'] = beauty['Order_Date'].dt.year

# Month

In [18]:
beauty['Month'] = beauty['Order_Date'].dt.month_name()

# Quarter

In [19]:
beauty['Quarter'] = beauty['Order_Date'].dt.quarter

In [20]:
beauty

,Order_ID,Order_Date,Region,Sales_Channel,Product_Name,Qty_Sold,Unit_Price,Discount_Percent,COGS_Per_Unit,Sales_Rep,Year,Month,Quarter
0,BT-00092,2023-01-01,West,Online,Matte Lipstick,52,310.0,34.2,94.18,Nidhi C,2023,January,1
1,BT-00531,2023-01-01,North,Modern Trade,BB Cream 30ml,4,560.0,8.6,231.90,Anjali M,2023,January,1
2,BT-00761,2023-01-01,Central,Salon Wholesale,Nail Polish Set (12pc),57,620.0,6.0,287.12,Sunita P,2023,January,1
3,BT-00770,2023-01-01,East,General Trade,Mascara,21,560.0,7.5,209.61,Sneha B,2023,January,1
4,BT-00806,2023-01-01,West,Salon Wholesale,Vitamin C Face Serum 30ml,8,770.0,26.1,231.15,Rahul D,2023,January,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,BT-02595,2023-12-31,North,Pharmacy,BB Cream 30ml,30,630.0,9.2,239.27,Anjali M,2023,December,4
4996,BT-03853,2023-12-31,West,General Trade,Night Repair Cream 50ml,8,910.0,38.3,351.08,Priya S,2023,December,4
4997,BT-04158,2023-12-31,East,Online,Hair Oil 200ml,9,310.0,12.9,118.02,Meena G,2023,December,4
4998,BT-04303,2023-12-31,Central,Salon Wholesale,Mascara,10,380.0,6.5,160.02,Vikram N,2023,December,4
4999,BT-04703,2023-12-31,Central,Salon Wholesale,Hair Oil 200ml,34,390.0,12.3,149.45,Suresh K,2023,December,4

# TOTAL REVENUE

In [21]:
beauty['Gross_Revenue'] = beauty['Qty_Sold'] * beauty['Unit_Price']

# Discount Amount

In [22]:
beauty['Discount_Amount'] = beauty['Gross_Revenue'] * (beauty['Discount_Percent'] / 100)

# Net Revenue

In [23]:
beauty['Net_Revenue'] = beauty['Gross_Revenue'] - beauty['Discount_Amount']

# Total COGS

In [24]:
beauty['Total_COGS'] = beauty['Qty_Sold'] * beauty['COGS_Per_Unit']

# Gross Profit

In [25]:
beauty['Gross_Profit'] = beauty['Net_Revenue'] - beauty['Total_COGS']

# Gross Margin %

In [26]:
beauty['Gross_Margin_Percent'] = (
    beauty['Gross_Profit'] / beauty['Net_Revenue']
) * 100

In [27]:
beauty

,Order_ID,Order_Date,Region,Sales_Channel,Product_Name,Qty_Sold,Unit_Price,Discount_Percent,COGS_Per_Unit,Sales_Rep,Year,Month,Quarter,Gross_Revenue,Discount_Amount,Net_Revenue,Total_COGS,Gross_Profit,Gross_Margin_Percent
0,BT-00092,2023-01-01,West,Online,Matte Lipstick,52,310.0,34.2,94.18,Nidhi C,2023,January,1,16120.0,5513.04,10606.96,4897.36,5709.60,53.828807
1,BT-00531,2023-01-01,North,Modern Trade,BB Cream 30ml,4,560.0,8.6,231.90,Anjali M,2023,January,1,2240.0,192.64,2047.36,927.60,1119.76,54.692873
2,BT-00761,2023-01-01,Central,Salon Wholesale,Nail Polish Set (12pc),57,620.0,6.0,287.12,Sunita P,2023,January,1,35340.0,2120.40,33219.60,16365.84,16853.76,50.734386
3,BT-00770,2023-01-01,East,General Trade,Mascara,21,560.0,7.5,209.61,Sneha B,2023,January,1,11760.0,882.00,10878.00,4401.81,6476.19,59.534749
4,BT-00806,2023-01-01,West,Salon Wholesale,Vitamin C Face Serum 30ml,8,770.0,26.1,231.15,Rahul D,2023,January,1,6160.0,1607.76,4552.24,1849.20,2703.04,59.378240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,BT-02595,2023-12-31,North,Pharmacy,BB Cream 30ml,30,630.0,9.2,239.27,Anjali M,2023,December,4,18900.0,1738.80,17161.20,7178.10,9983.10,58.172505
4996,BT-03853,2023-12-31,West,General Trade,Night Repair Cream 50ml,8,910.0,38.3,351.08,Priya S,2023,December,4,7280.0,2788.24,4491.76,2808.64,1683.12,37.471281
4997,BT-04158,2023-12-31,East,Online,Hair Oil 200ml,9,310.0,12.9,118.02,Meena G,2023,December,4,2790.0,359.91,2430.09,1062.18,1367.91,56.290508
4998,BT-04303,2023-12-31,Central,Salon Wholesale,Mascara,10,380.0,6.5,160.02,Vikram N,2023,December,4,3800.0,247.00,3553.00,1600.20,1952.80,54.962004
4999,BT-04703,2023-12-31,Central,Salon Wholesale,Hair Oil 200ml,34,390.0,12.3,149.45,Suresh K,2023,December,4,13260.0,1630.98,11629.02,5081.30,6547.72,56.305002

# Covert all the column lower()

In [28]:
beauty.columns = beauty.columns.str.lower()

In [29]:
beauty

,order_id,order_date,region,sales_channel,product_name,qty_sold,unit_price,discount_percent,cogs_per_unit,sales_rep,year,month,quarter,gross_revenue,discount_amount,net_revenue,total_cogs,gross_profit,gross_margin_percent
0,BT-00092,2023-01-01,West,Online,Matte Lipstick,52,310.0,34.2,94.18,Nidhi C,2023,January,1,16120.0,5513.04,10606.96,4897.36,5709.60,53.828807
1,BT-00531,2023-01-01,North,Modern Trade,BB Cream 30ml,4,560.0,8.6,231.90,Anjali M,2023,January,1,2240.0,192.64,2047.36,927.60,1119.76,54.692873
2,BT-00761,2023-01-01,Central,Salon Wholesale,Nail Polish Set (12pc),57,620.0,6.0,287.12,Sunita P,2023,January,1,35340.0,2120.40,33219.60,16365.84,16853.76,50.734386
3,BT-00770,2023-01-01,East,General Trade,Mascara,21,560.0,7.5,209.61,Sneha B,2023,January,1,11760.0,882.00,10878.00,4401.81,6476.19,59.534749
4,BT-00806,2023-01-01,West,Salon Wholesale,Vitamin C Face Serum 30ml,8,770.0,26.1,231.15,Rahul D,2023,January,1,6160.0,1607.76,4552.24,1849.20,2703.04,59.378240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,BT-02595,2023-12-31,North,Pharmacy,BB Cream 30ml,30,630.0,9.2,239.27,Anjali M,2023,December,4,18900.0,1738.80,17161.20,7178.10,9983.10,58.172505
4996,BT-03853,2023-12-31,West,General Trade,Night Repair Cream 50ml,8,910.0,38.3,351.08,Priya S,2023,December,4,7280.0,2788.24,4491.76,2808.64,1683.12,37.471281
4997,BT-04158,2023-12-31,East,Online,Hair Oil 200ml,9,310.0,12.9,118.02,Meena G,2023,December,4,2790.0,359.91,2430.09,1062.18,1367.91,56.290508
4998,BT-04303,2023-12-31,Central,Salon Wholesale,Mascara,10,380.0,6.5,160.02,Vikram N,2023,December,4,3800.0,247.00,3553.00,1600.20,1952.80,54.962004
4999,BT-04703,2023-12-31,Central,Salon Wholesale,Hair Oil 200ml,34,390.0,12.3,149.45,Suresh K,2023,December,4,13260.0,1630.98,11629.02,5081.30,6547.72,56.305002

#  A/B Testing — Discount Impact on Revenue & Margin
# Does giving a higher discount actually cause a real difference in revenue, margin, and quantity sold — or does it just look different by chance?

In [30]:
from scipy import stats

# Split into A/B groups based on discount tier
group_a = beauty[beauty['discount_percent'] <= 10]   # Low discount (control)
group_b = beauty[beauty['discount_percent'] > 20]    # High discount (treatment)

print('Group A (<=10% discount) size:', len(group_a))
print('Group B (>20% discount) size:', len(group_b))

Group A (<=10% discount) size: 1736
Group B (>20% discount) size: 1607

In [31]:
results = []

for metric in ['net_revenue', 'gross_margin_percent', 'qty_sold']:
    a = group_a[metric]
    b = group_b[metric]
    t_stat, p_val = stats.ttest_ind(a, b, equal_var=False)
    results.append({
        'metric': metric,
        'mean_group_a': round(a.mean(), 2),
        'mean_group_b': round(b.mean(), 2),
        't_stat': round(t_stat, 3),
        'p_value': round(p_val, 5),
        'significant (p<0.05)': p_val < 0.05
    })

ab_results = pd.DataFrame(results)
ab_results

,metric,mean_group_a,mean_group_b,t_stat,p_value,significant (p<0.05)
0,net_revenue,15782.85,12089.01,7.841,0.00000,True
1,gross_margin_percent,60.81,48.44,42.717,0.00000,True
2,qty_sold,30.53,30.88,-0.590,0.55503,False

Offering discounts above 20% is not earning GlowCart extra sales volume — customers buy roughly the same amount whether the discount is 8% or 30%. 
But it is significantly eroding both revenue and margin. 
The data says the high-discount strategy is a straight loss with no upside, not a volume-for-margin tradeoff.

# Save The data Cleaning file

In [32]:
beauty.to_csv("cleaned_glowcart.csv", index=False)

In [33]:
import os

In [34]:
os.path.exists("cleaned_glowcart.csv")

True

# Connect cleaned data set  from mysql

In [35]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\shushree swain\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: pymysql in c:\users\shushree swain\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\shushree swain\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\shushree swain\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Note: you may need to restart the kernel to use updated packages.

In [36]:
from sqlalchemy import create_engine

In [38]:
engine = create_engine(
    'mysql+pymysql://root:yourpass@localhost:3306/glowcart_db' # enter your password
)

# Upload dataframe to SQL

In [39]:
beauty.to_sql(
    'glowcart_sales',
    engine,
    if_exists='replace',
    index=False
)

5000